FROM python:latest

COPY users/app.py /app/
COPY users/user.sql /app/
COPY key.txt /app/

WORKDIR /app

RUN pip3 install flask requests

EXPOSE 5000

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
