FROM python:latest

COPY app.py /app/
COPY listings.sql /app/

WORKDIR /app

RUN pip3 install flask requests

EXPOSE 5000

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
